# Generated by Django 4.1.3 on 2022-11-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='delivery',
            field=models.CharField(choices=[('Pick Up Only', 'Pick Up Only'), ('By Post Only', 'By Post Only'), ('Pick Up or by Post', 'Pick Up or by Post')], max_length=30),
        ),
    ]
